#!/bin/bash
# NEXTFLOW TASK: Runpermutation (15)
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}

nxf_container_env() {
cat << EOF
export PATH="\$PATH:/media/vikas/fast/data/TEBAG/publication/scripts/evoproj/bin"
EOF
}

nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf $exit_status > /media/vikas/fast/data/TEBAG/publication/scripts/evoproj/work2/98/736adb7e869f8bd71f7aa025c80e56/.exitcode
    set +u
    [[ "$tee1" ]] && kill $tee1 2>/dev/null
    [[ "$tee2" ]] && kill $tee2 2>/dev/null
    [[ "$ctmp" ]] && rm -rf $ctmp || true
    docker rm $NXF_BOXID &>/dev/null || true
    exit $exit_status
}

on_term() {
    set +e
    docker kill $NXF_BOXID
}

nxf_launch() {
    docker run -i --cpus 7.0 --memory 16384m -v /media/vikas/fast/data/TEBAG/publication/scripts/evoproj:/media/vikas/fast/data/TEBAG/publication/scripts/evoproj -w "$PWD" --name $NXF_BOXID vpeddu/evoproj:v1 /bin/bash -c "eval $(nxf_container_env); /bin/bash /media/vikas/fast/data/TEBAG/publication/scripts/evoproj/work2/98/736adb7e869f8bd71f7aa025c80e56/.command.sh"
}

nxf_stage() {
    true
    # stage input files
    rm -f chm13v2.0_HAP-1.H3K4me3.bb
    rm -f chm13v2.0_SJSA1.H3K4me3.bb
    rm -f chm13v2.0_SJCRH30.H3K4me3.bb
    rm -f chm13v2.0_MG63.H3K4me3.bb
    rm -f LTR79_human.bed
    rm -f chm13v2.0.fa.fai
    ln -s /media/vikas/fast/data/TEBAG/publication/scripts/evoproj/bigbeds/chm13v2.0_HAP-1.H3K4me3.bb chm13v2.0_HAP-1.H3K4me3.bb
    ln -s /media/vikas/fast/data/TEBAG/publication/scripts/evoproj/bigbeds/chm13v2.0_SJSA1.H3K4me3.bb chm13v2.0_SJSA1.H3K4me3.bb
    ln -s /media/vikas/fast/data/TEBAG/publication/scripts/evoproj/bigbeds/chm13v2.0_SJCRH30.H3K4me3.bb chm13v2.0_SJCRH30.H3K4me3.bb
    ln -s /media/vikas/fast/data/TEBAG/publication/scripts/evoproj/bigbeds/chm13v2.0_MG63.H3K4me3.bb chm13v2.0_MG63.H3K4me3.bb
    ln -s /media/vikas/fast/data/TEBAG/publication/scripts/evoproj/work2/5b/b241485088ff3c3f1ca562750e34a6/LTR79_human.bed LTR79_human.bed
    ln -s /media/vikas/fast/data/TEBAG/publication/scripts/evoproj/work/test/chm13v2.0.fa.fai chm13v2.0.fa.fai
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    export NXF_BOXID="nxf-$(dd bs=18 count=1 if=/dev/urandom 2>/dev/null | base64 | tr +/ 0A)"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /media/vikas/fast/data/TEBAG/publication/scripts/evoproj/work2/98/736adb7e869f8bd71f7aa025c80e56/.command.begin
    set +u
    # beforeScript directive
    chmod o+rw .
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    nxf_stage

    set +e
    ctmp=$(set +u; nxf_mktemp /dev/shm 2>/dev/null || nxf_mktemp $TMPDIR)
    local cout=$ctmp/.command.out; mkfifo $cout
    local cerr=$ctmp/.command.err; mkfifo $cerr
    tee .command.out < $cout &
    tee1=$!
    tee .command.err < $cerr >&2 &
    tee2=$!
    ( nxf_launch ) >$cout 2>$cerr &
    pid=$!
    wait $pid || nxf_main_ret=$?
    wait $tee1 $tee2
    nxf_unstage
}

$NXF_ENTRY
